/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TechniquesRouteImport } from './routes/techniques'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TunerRouteImport } from './routes/tuner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniquesRoute = TechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ResultsRoute: typeof ResultsRoute
  SkillsRoute: typeof SkillsRoute
  TechniquesRoute: typeof TechniquesRoute
  TheoryRoute: typeof TheoryRoute
  TodayRoute: typeof TodayRoute
  TunerRoute: typeof TunerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techniques': {
      id: '/techniques'
      path: '/techniques'
      fullPath: '/techniques'
      preLoaderRoute: typeof TechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ResultsRoute: ResultsRoute,
  SkillsRoute: SkillsRoute,
  TechniquesRoute: TechniquesRoute,
  TheoryRoute: TheoryRoute,
  TodayRoute: TodayRoute,
  TunerRoute: TunerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
