/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MilestoneRouteImport } from './routes/milestone'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as StartRouteImport } from './routes/start'
import { Route as TechniquesRouteImport } from './routes/techniques'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as ApiCoachRouteImport } from './routes/api/coach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestoneRoute = MilestoneRouteImport.update({
  id: '/milestone',
  path: '/milestone',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniquesRoute = TechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/milestone': typeof MilestoneRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/start': typeof StartRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/milestone': typeof MilestoneRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/start': typeof StartRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/learn': typeof LearnRoute
  '/milestone': typeof MilestoneRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/results': typeof ResultsRoute
  '/skills': typeof SkillsRoute
  '/start': typeof StartRoute
  '/techniques': typeof TechniquesRoute
  '/theory': typeof TheoryRoute
  '/today': typeof TodayRoute
  '/tuner': typeof TunerRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/learn'
    | '/milestone'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/start'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
    | '/api/coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/learn'
    | '/milestone'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/start'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
    | '/api/coach'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/learn'
    | '/milestone'
    | '/practice'
    | '/progress'
    | '/results'
    | '/skills'
    | '/start'
    | '/techniques'
    | '/theory'
    | '/today'
    | '/tuner'
    | '/api/coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  LearnRoute: typeof LearnRoute
  MilestoneRoute: typeof MilestoneRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ResultsRoute: typeof ResultsRoute
  SkillsRoute: typeof SkillsRoute
  StartRoute: typeof StartRoute
  TechniquesRoute: typeof TechniquesRoute
  TheoryRoute: typeof TheoryRoute
  TodayRoute: typeof TodayRoute
  TunerRoute: typeof TunerRoute
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestone': {
      id: '/milestone'
      path: '/milestone'
      fullPath: '/milestone'
      preLoaderRoute: typeof MilestoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techniques': {
      id: '/techniques'
      path: '/techniques'
      fullPath: '/techniques'
      preLoaderRoute: typeof TechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  LearnRoute: LearnRoute,
  MilestoneRoute: MilestoneRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ResultsRoute: ResultsRoute,
  SkillsRoute: SkillsRoute,
  StartRoute: StartRoute,
  TechniquesRoute: TechniquesRoute,
  TheoryRoute: TheoryRoute,
  TodayRoute: TodayRoute,
  TunerRoute: TunerRoute,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
