import type { ChordShape, Lesson } from "./types";

export const TUNING = ["E2", "A2", "D3", "G3", "B3", "E4"] as const;
export const STRING_NAMES = ["E", "A", "D", "G", "B", "e"] as const;

/** Frequencies for open strings, low E → high e. */
export const OPEN_FREQ = [82.41, 110.0, 146.83, 196.0, 246.94, 329.63];

export const CHORDS: Record<string, ChordShape> = {
  Em: {
    id: "Em",
    name: "Em",
    frets: [0, 2, 2, 0, 0, 0],
    fingers: [0, 2, 3, 0, 0, 0],
    notes: ["E", "B", "E", "G", "B", "E"],
  },
  G: {
    id: "G",
    name: "G",
    frets: [3, 2, 0, 0, 0, 3],
    fingers: [2, 1, 0, 0, 0, 3],
    notes: ["G", "B", "D", "G", "B", "G"],
  },
  C: {
    id: "C",
    name: "C",
    frets: [null, 3, 2, 0, 1, 0],
    fingers: [null, 3, 2, 0, 1, 0],
    notes: ["C", "E", "G", "C", "E"],
  },
  D: {
    id: "D",
    name: "D",
    frets: [null, null, 0, 2, 3, 2],
    fingers: [null, null, 0, 1, 3, 2],
    notes: ["D", "A", "D", "F#"],
  },
  Am: {
    id: "Am",
    name: "Am",
    frets: [null, 0, 2, 2, 1, 0],
    fingers: [null, 0, 2, 3, 1, 0],
    notes: ["A", "E", "A", "C", "E"],
  },
  E: {
    id: "E",
    name: "E",
    frets: [0, 2, 2, 1, 0, 0],
    fingers: [0, 2, 3, 1, 0, 0],
    notes: ["E", "B", "E", "G#", "B", "E"],
  },
  A: {
    id: "A",
    name: "A",
    frets: [null, 0, 2, 2, 2, 0],
    fingers: [null, 0, 1, 2, 3, 0],
    notes: ["A", "E", "A", "C#", "E"],
  },
};

export const TRACKS = [
  { id: "track_guitar_foundations", name: "Foundations" },
  { id: "track_guitar_open_chords", name: "Open chords" },
  { id: "track_guitar_chord_switching", name: "Switching" },
  { id: "track_guitar_rhythm", name: "Rhythm" },
  { id: "track_guitar_performance", name: "Songs" },
] as const;

export const LESSONS: Lesson[] = [
  {
    id: "lesson_guitar_orientation_01",
    title: "Meet the guitar",
    skill: "guitar_orientation",
    trackId: "track_guitar_foundations",
    order: 1,
    type: "skill",
    objectives: ["Name the six strings", "Find the neck, frets, and body"],
    chords: [],
    pattern: "D",
    bars: 4,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_guitar_tuning_01",
    title: "Tune without panic",
    skill: "guitar_tuning",
    trackId: "track_guitar_foundations",
    order: 2,
    type: "warmup",
    objectives: ["Hear low-to-high string order", "Match a reference pitch"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_guitar_orientation_01"],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_guitar_open_strings_01",
    title: "Open string sound check",
    skill: "open_strings",
    trackId: "track_guitar_foundations",
    order: 3,
    type: "warmup",
    objectives: ["Pluck each string cleanly", "Mute the rest"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_guitar_tuning_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_guitar_pick_downstrokes_01",
    title: "Downstrokes on the beat",
    skill: "pick_downstrokes",
    trackId: "track_guitar_foundations",
    order: 4,
    type: "rhythm",
    objectives: ["Steady downstrokes", "Stay with a slow click"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_guitar_open_strings_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_guitar_count_quarters_01",
    title: "Count 1-2-3-4",
    skill: "quarter_counting",
    trackId: "track_guitar_foundations",
    order: 5,
    type: "rhythm",
    objectives: ["Count four beats", "Land on one"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 76,
    prerequisites: ["lesson_guitar_pick_downstrokes_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_guitar_em_chord_01",
    title: "Your first chord: Em",
    skill: "em_chord",
    trackId: "track_guitar_open_chords",
    order: 6,
    type: "chord",
    objectives: ["Build the Em shape", "Strum only intended strings"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_guitar_count_quarters_01"],
    masteryRequired: 0.75,
    why: "First chord in Night Bus.",
    criteria: ["The shape is down before the strum"],
  },
  {
    id: "lesson_guitar_g_chord_01",
    title: "Big G chord",
    skill: "g_chord",
    trackId: "track_guitar_open_chords",
    order: 7,
    type: "chord",
    objectives: ["Build G", "Land fingers together"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_guitar_em_chord_01"],
    masteryRequired: 0.75,
    why: "The other half of Night Bus.",
    criteria: ["The shape is down before the strum"],
  },
  {
    id: "lesson_guitar_c_chord_01",
    title: "C without tension",
    skill: "c_chord",
    trackId: "track_guitar_open_chords",
    order: 8,
    type: "chord",
    objectives: ["Build C", "Keep the wrist soft"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_guitar_g_chord_01"],
    masteryRequired: 0.75,
    why: "Lives in Kitchen Radio.",
    criteria: ["The shape is down before the strum"],
  },
  {
    id: "lesson_guitar_d_chord_01",
    title: "D and small strums",
    skill: "d_chord",
    trackId: "track_guitar_open_chords",
    order: 9,
    type: "chord",
    objectives: ["Build D", "Aim at the top four strings"],
    chords: ["D"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_guitar_g_chord_01"],
    masteryRequired: 0.75,
    why: "The V in Kitchen Radio.",
    criteria: ["The shape is down before the strum"],
  },
  {
    id: "lesson_guitar_am_chord_01",
    title: "A minor shape",
    skill: "am_chord",
    trackId: "track_guitar_open_chords",
    order: 10,
    type: "chord",
    objectives: ["Build Am", "Hear the minor colour"],
    chords: ["Am"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_guitar_c_chord_01"],
    masteryRequired: 0.75,
    why: "The dark colour next to C.",
    criteria: ["The shape is down before the strum"],
  },
  {
    id: "lesson_guitar_respond_colour_01",
    title: "Bright or dark",
    skill: "harmonic_colour",
    trackId: "track_guitar_open_chords",
    order: 11,
    type: "skill",
    objectives: ["Hear C, then Am", "Name same colour or different"],
    chords: ["C", "Am"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_guitar_am_chord_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Kitchen Radio",
    listenPrompt: { a: "C", b: "Am", ask: "Same colour or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "C is bright. Am is the same neighbourhood, darker.",
  },
  {
    id: "lesson_guitar_em_g_switch_01",
    title: "Em ↔ G switch",
    skill: "open_chord_switching",
    trackId: "track_guitar_chord_switching",
    order: 11,
    type: "transition",
    objectives: ["Switch without stopping the pulse", "Prepare two beats early"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 16,
    bpm: 68,
    prerequisites: ["lesson_guitar_g_chord_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Night Bus",
    criteria: ["The pulse doesn't stop", "Prepare two beats early"],
    why: "This switch is Night Bus.",
    interpret: "Keep the pulse. The bus doesn't wait.",
  },
  {
    id: "lesson_guitar_respond_bus_01",
    title: "The two colours",
    skill: "harmonic_colour",
    trackId: "track_guitar_open_chords",
    order: 11,
    type: "skill",
    objectives: ["Hear Em, then G", "Name same colour or different"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_guitar_song_first_two_chord_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Night Bus",
    listenPrompt: { a: "Em", b: "G", ask: "Same colour or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Night Bus uses both. Name the difference.",
  },
  {
    id: "lesson_guitar_create_hang_01",
    title: "Your hang",
    skill: "create_hang",
    trackId: "track_guitar_performance",
    order: 12,
    type: "song",
    objectives: ["Pick stay on Em, or switch to G", "Play the one you picked"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_guitar_song_first_two_chord_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["Em", "Em–G"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
  {
    id: "lesson_guitar_c_g_switch_01",
    title: "C ↔ G switch",
    skill: "open_chord_switching",
    trackId: "track_guitar_chord_switching",
    order: 12,
    type: "transition",
    objectives: ["Move shared fingers efficiently", "Keep the count alive"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 16,
    bpm: 68,
    prerequisites: ["lesson_guitar_c_chord_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    criteria: ["The pulse doesn't stop", "Shared fingers travel together"],
    why: "This switch lives in Kitchen Radio.",
  },
  {
    id: "lesson_guitar_g_d_switch_01",
    title: "G ↔ D switch",
    skill: "open_chord_switching",
    trackId: "track_guitar_chord_switching",
    order: 13,
    type: "transition",
    objectives: ["Target the D strings", "Don't restart after a miss"],
    chords: ["G", "D"],
    pattern: "D",
    bars: 16,
    bpm: 68,
    prerequisites: ["lesson_guitar_d_chord_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    criteria: ["The pulse doesn't stop", "Don't restart after a miss"],
    why: "G to D is the radio's lift.",
  },
  {
    id: "lesson_guitar_am_c_switch_01",
    title: "Am ↔ C switch",
    skill: "open_chord_switching",
    trackId: "track_guitar_chord_switching",
    order: 14,
    type: "transition",
    objectives: ["Use an anchor finger", "Hear the close movement"],
    chords: ["Am", "C"],
    pattern: "D",
    bars: 16,
    bpm: 70,
    prerequisites: ["lesson_guitar_am_chord_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    criteria: ["The pulse doesn't stop", "Keep an anchor finger"],
    why: "Am to C is the dark-to-bright move.",
  },
  {
    id: "lesson_guitar_four_chord_loop_01",
    title: "Kitchen Radio",
    skill: "four_chord_loop",
    trackId: "track_guitar_performance",
    order: 16,
    type: "song",
    objectives: ["Play G–D–Em–C", "Finish an 8-bar cycle"],
    chords: ["G", "D", "Em", "C"],
    pattern: "D",
    bars: 16,
    bpm: 72,
    prerequisites: [
      "lesson_guitar_c_g_switch_01",
      "lesson_guitar_g_d_switch_01",
      "lesson_guitar_am_c_switch_01",
    ],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    criteria: ["The loop finishes", "One chord per two bars"],
    why: "The four chords the radio already uses.",
    interpret: "Play it like it's on in the other room.",
  },
  {
    id: "lesson_guitar_strum_eighths_01",
    title: "Eighth-note engine",
    skill: "eighth_strumming",
    trackId: "track_guitar_rhythm",
    order: 16,
    type: "rhythm",
    objectives: ["Feel 1-and-2-and", "Keep the hand moving"],
    chords: ["Em"],
    pattern: "DUDU",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_guitar_count_quarters_01"],
    masteryRequired: 0.75,
    why: "The hand is the drummer.",
    criteria: ["The hand keeps moving", "Land on one"],
    interpret: "Don't freeze. Misses get absorbed.",
  },
  {
    id: "lesson_guitar_strum_down_up_01",
    title: "Down-up strum",
    skill: "down_up_strumming",
    trackId: "track_guitar_rhythm",
    order: 17,
    type: "rhythm",
    objectives: ["Alternate down and up", "Don't freeze on a miss"],
    chords: ["Em", "G"],
    pattern: "DUDU",
    bars: 16,
    bpm: 84,
    prerequisites: ["lesson_guitar_strum_eighths_01"],
    masteryRequired: 0.75,
    repertoire: "Night Bus",
    why: "Night Bus with a moving hand.",
    criteria: ["The hand keeps moving", "Don't freeze on a miss"],
  },
  {
    id: "lesson_guitar_strum_pattern_pop_01",
    title: "Pop pattern",
    skill: "down_up_strumming",
    trackId: "track_guitar_rhythm",
    order: 18,
    type: "rhythm",
    objectives: ["Play D DU UDU", "Loop it across chords"],
    chords: ["G", "D", "Em", "C"],
    pattern: "D-DU-UDU",
    bars: 16,
    bpm: 88,
    prerequisites: ["lesson_guitar_strum_down_up_01", "lesson_guitar_four_chord_loop_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    why: "The radio pattern on the four-chord loop.",
    interpret: "Keep the hand like a drummer who won't stop.",
    criteria: ["The hand keeps moving", "Land on one"],
  },
  {
    id: "lesson_guitar_song_first_two_chord_01",
    title: "Night Bus",
    skill: "two_chord_song",
    trackId: "track_guitar_performance",
    order: 21,
    type: "song",
    objectives: ["Play an Em–G loop", "Keep the pulse through the change"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_guitar_em_g_switch_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Night Bus",
    criteria: ["The loop finishes", "The pulse holds through the change"],
    why: "Two chords that sit under a slow song.",
    interpret: "Play it like the last bus home.",
  },
];

export const FIRST_PROMISE =
  "In the first real session, you play Night Bus — two chords, a clean down-strum pulse.";

export const FOUNDATION_LESSONS = [
  "lesson_guitar_orientation_01",
  "lesson_guitar_tuning_01",
  "lesson_guitar_open_strings_01",
] as const;

export function lessonById(id: string) {
  return LESSONS.find((l) => l.id === id) ?? null;
}

export function isUnlocked(id: string, mastery: Record<string, number>) {
  const lesson = lessonById(id);
  if (!lesson) return false;
  return lesson.prerequisites.every((p) => (mastery[p] ?? 0) >= (lessonById(p)?.masteryRequired ?? 0.7));
}

export function nextLesson(mastery: Record<string, number>) {
  return LESSONS.find((l) => isUnlocked(l.id, mastery) && (mastery[l.id] ?? 0) < l.masteryRequired) ?? LESSONS[LESSONS.length - 1];
}

export function fretToFreq(stringIndex: number, fret: number) {
  return OPEN_FREQ[stringIndex] * Math.pow(2, fret / 12);
}
