import type { Lesson, PlanItem } from "./types.ts";
import { LESSONS as GUITAR_LESSONS, TRACKS as GUITAR_TRACKS, FIRST_PROMISE as GUITAR_PROMISE } from "./guitar.ts";

export type InstrumentId = "guitar" | "piano" | "ukulele" | "bass" | "drums" | "vocals" | "mandolin" | "banjo" | "violin";

export type InstrumentDef = {
  id: InstrumentId;
  name: string;
  kicker: string;
  promise: string;
  family: "strings" | "keys" | "rhythm" | "voice";
  surface: "strings" | "keys" | "pads" | "voice";
  stringNames: string[];
  openFreq: number[];
  openPc: number[];
  firstChords: string[];
  theoryNeck: "guitar" | "piano" | "four" | "none";
  /** Indexes of the strings the theory neck shows; omitted means all strings. */
  theoryStrings?: number[];
};

export const INSTRUMENTS: InstrumentDef[] = [
  {
    id: "guitar",
    name: "Guitar",
    kicker: "6-string",
    promise: "In the first real session, you play Night Bus — two chords, a clean down-strum pulse.",
    family: "strings",
    surface: "strings",
    stringNames: ["E", "A", "D", "G", "B", "e"],
    openFreq: [82.41, 110, 146.83, 196, 246.94, 329.63],
    openPc: [4, 9, 2, 7, 11, 4],
    firstChords: ["Em", "G"],
    theoryNeck: "guitar",
  },
  {
    id: "piano",
    name: "Piano",
    kicker: "Keys",
    promise: "Find middle C, then play a C–G cadence. Two chords. Home and gravity.",
    family: "keys",
    surface: "keys",
    stringNames: ["C", "D", "E", "F", "G", "A", "B"],
    openFreq: [261.63],
    openPc: [0],
    firstChords: ["C", "G"],
    theoryNeck: "piano",
  },
  {
    id: "ukulele",
    name: "Ukulele",
    kicker: "GCEA",
    promise: "Four strings, one C chord, then a C–G loop you can actually sing over.",
    family: "strings",
    surface: "strings",
    stringNames: ["G", "C", "E", "A"],
    openFreq: [392.0, 261.63, 329.63, 440.0],
    openPc: [7, 0, 4, 9],
    firstChords: ["C", "G"],
    theoryNeck: "four",
  },
  {
    id: "bass",
    name: "Bass",
    kicker: "EADG",
    promise: "Roots on the pulse. Em to G, one note at a time, locked to the kick.",
    family: "strings",
    surface: "strings",
    stringNames: ["E", "A", "D", "G"],
    openFreq: [41.2, 55.0, 73.42, 98.0],
    openPc: [4, 9, 2, 7],
    firstChords: ["Em", "G"],
    theoryNeck: "four",
  },
  {
    id: "drums",
    name: "Drums",
    kicker: "Kit",
    promise: "Kick on one. Snare on two and four. That’s a backbeat — the whole song sits on it.",
    family: "rhythm",
    surface: "pads",
    stringNames: ["Kick", "Snare", "Hat", "Tom"],
    openFreq: [60, 180, 8000, 120],
    openPc: [0, 0, 0, 0],
    firstChords: [],
    theoryNeck: "none",
  },
  {
    id: "vocals",
    name: "Vocals",
    kicker: "Pitch",
    promise: "Match a C, hold it for four beats. Breath is the instrument.",
    family: "voice",
    surface: "voice",
    stringNames: ["C"],
    openFreq: [261.63],
    openPc: [0],
    firstChords: ["C"],
    theoryNeck: "piano",
  },
  {
    id: "mandolin",
    name: "Mandolin",
    kicker: "GDAE",
    promise: "Two-finger G and C, then a chop on two and four. The pulse lives in your wrist.",
    family: "strings",
    surface: "strings",
    stringNames: ["G", "D", "A", "E"],
    openFreq: [196.0, 293.66, 440.0, 659.25],
    openPc: [7, 2, 9, 4],
    firstChords: ["G", "C"],
    theoryNeck: "four",
  },
  {
    id: "banjo",
    name: "Banjo",
    kicker: "gDGBD",
    promise: "Open strings already make a G chord. Add one roll and it moves.",
    family: "strings",
    surface: "strings",
    stringNames: ["g", "D", "G", "B", "D"],
    openFreq: [392.0, 146.83, 196.0, 246.94, 293.66],
    openPc: [7, 2, 7, 11, 2],
    firstChords: ["G", "D7"],
    theoryNeck: "four",
    theoryStrings: [1, 2, 3, 4],
  },
  {
    id: "violin",
    name: "Violin",
    kicker: "GDAE",
    promise: "One open string, one full bow. Then a first finger. The sound is in the bow speed.",
    family: "strings",
    surface: "strings",
    stringNames: ["G", "D", "A", "E"],
    openFreq: [196.0, 293.66, 440.0, 659.25],
    openPc: [7, 2, 9, 4],
    firstChords: [],
    theoryNeck: "none",
  },
];

export function instrumentById(id: string): InstrumentDef {
  return INSTRUMENTS.find((i) => i.id === id) ?? INSTRUMENTS[0];
}

export function isInstrumentId(id: unknown): id is InstrumentId {
  return typeof id === "string" && INSTRUMENTS.some((i) => i.id === id);
}

/** The instrument as the theory neck sees it: only the strings that run the full neck. */
export function theoryNeckDef(inst: InstrumentDef): InstrumentDef {
  const keep = inst.theoryStrings;
  if (!keep) return inst;
  return {
    ...inst,
    stringNames: keep.map((i) => inst.stringNames[i]),
    openFreq: keep.map((i) => inst.openFreq[i]),
    openPc: keep.map((i) => inst.openPc[i]),
  };
}

const PIANO_LESSONS: Lesson[] = [
  {
    id: "lesson_piano_middle_c_01",
    title: "Find middle C",
    skill: "middle_c",
    trackId: "track_piano_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Find C below the two black keys"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_piano_c_triad_01",
    title: "C major triad",
    skill: "c_triad",
    trackId: "track_piano_triads",
    order: 2,
    type: "chord",
    objectives: ["Play C–E–G together", "Hear the bright third"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_piano_middle_c_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_piano_g_triad_01",
    title: "G major triad",
    skill: "g_triad",
    trackId: "track_piano_triads",
    order: 3,
    type: "chord",
    objectives: ["Play G–B–D", "Keep the hand quiet"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_piano_c_triad_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_piano_cg_cadence_01",
    title: "Home and gravity",
    skill: "cg_cadence",
    trackId: "track_piano_cadences",
    order: 4,
    type: "song",
    objectives: ["I to V and back", "Feel G pull home"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_piano_g_triad_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Home and gravity",
    criteria: ["The loop finishes", "G pulls home"],
    why: "I to V. Home, then gravity.",
    interpret: "Let G pull you back.",
  },
  {
    id: "lesson_piano_am_01",
    title: "A minor colour",
    skill: "am_triad",
    trackId: "track_piano_triads",
    order: 5,
    type: "chord",
    objectives: ["Play A–C–E", "Hear the flattened third"],
    chords: ["Am"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_piano_c_triad_01"],
    masteryRequired: 0.75,
    why: "The dark colour next to C.",
  },
  {
    id: "lesson_piano_f_01",
    title: "F major triad",
    skill: "f_triad",
    trackId: "track_piano_triads",
    order: 6,
    type: "chord",
    objectives: ["Play F–A–C", "The IV before the loop"],
    chords: ["F"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_piano_c_triad_01"],
    masteryRequired: 0.75,
    why: "The IV before Kitchen Radio.",
  },
  {
    id: "lesson_piano_respond_cadence_01",
    title: "Home or gravity",
    skill: "piano_listen",
    trackId: "track_piano_cadences",
    order: 7,
    type: "skill",
    objectives: ["Hear C, then G", "Name same chord or different"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_piano_cg_cadence_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Home and gravity",
    listenPrompt: { a: "C", b: "G", ask: "Same chord or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Home and gravity. Name which one moved.",
  },
  {
    id: "lesson_piano_respond_colour_01",
    title: "Bright or dark",
    skill: "piano_colour",
    trackId: "track_piano_triads",
    order: 8,
    type: "skill",
    objectives: ["Hear C, then Am", "Name same colour or different"],
    chords: ["C", "Am"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_piano_am_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Kitchen Radio",
    listenPrompt: { a: "C", b: "Am", ask: "Same colour or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "C is bright. Am is the same neighbourhood, darker.",
  },
  {
    id: "lesson_piano_four_01",
    title: "Kitchen Radio",
    skill: "piano_four",
    trackId: "track_piano_cadences",
    order: 9,
    type: "song",
    objectives: ["C–G–Am–F", "One chord per two bars"],
    chords: ["C", "G", "Am", "F"],
    pattern: "D",
    bars: 16,
    bpm: 80,
    prerequisites: ["lesson_piano_cg_cadence_01", "lesson_piano_am_01", "lesson_piano_f_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Kitchen Radio",
    criteria: ["The loop finishes", "One chord per two bars"],
    why: "The four chords the radio already uses.",
    interpret: "Play it like it's on in the other room.",
  },
  {
    id: "lesson_piano_create_hang_01",
    title: "Your hang",
    skill: "piano_create",
    trackId: "track_piano_cadences",
    order: 10,
    type: "song",
    objectives: ["Stay on C, or walk to G", "Play the one you picked"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_piano_cg_cadence_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["C", "C–G"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const UKE_LESSONS: Lesson[] = [
  {
    id: "lesson_uke_open_01",
    title: "Open GCEA",
    skill: "uke_open",
    trackId: "track_uke_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Pluck G C E A in order"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_uke_c_01",
    title: "C on four strings",
    skill: "uke_c",
    trackId: "track_uke_chords",
    order: 2,
    type: "chord",
    objectives: ["Ring finger, third fret, A string"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_uke_open_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_uke_g_01",
    title: "G shape",
    skill: "uke_g",
    trackId: "track_uke_chords",
    order: 3,
    type: "chord",
    objectives: ["Three fingers, one beat of setup"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_uke_c_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_uke_cg_01",
    title: "Dock Loop",
    skill: "uke_cg",
    trackId: "track_uke_songs",
    order: 4,
    type: "song",
    objectives: ["Switch without stopping the pulse"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_uke_g_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Dock Loop",
    criteria: ["The loop finishes", "The pulse holds through the change"],
    why: "The porch loop you can sing over.",
    interpret: "Play it like you're outside.",
  },
  {
    id: "lesson_uke_respond_dock_01",
    title: "Same chord or different",
    skill: "uke_listen",
    trackId: "track_uke_songs",
    order: 5,
    type: "skill",
    objectives: ["Hear C, then G", "Name same chord or different"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_uke_cg_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Dock Loop",
    listenPrompt: { a: "C", b: "G", ask: "Same chord or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Dock Loop uses both. Name the difference.",
  },
  {
    id: "lesson_uke_am_01",
    title: "Am on four",
    skill: "uke_am",
    trackId: "track_uke_chords",
    order: 5,
    type: "chord",
    objectives: ["Second fret, G string", "Hear the minor colour"],
    chords: ["Am"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_uke_c_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_uke_f_01",
    title: "F shape",
    skill: "uke_f",
    trackId: "track_uke_chords",
    order: 6,
    type: "chord",
    objectives: ["Two fingers, light squeeze"],
    chords: ["F"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_uke_am_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_uke_respond_colour_01",
    title: "Bright or dark",
    skill: "uke_colour",
    trackId: "track_uke_chords",
    order: 7,
    type: "skill",
    objectives: ["Hear C, then Am", "Name same colour or different"],
    chords: ["C", "Am"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_uke_am_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Dock Loop",
    listenPrompt: { a: "C", b: "Am", ask: "Same colour or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "C is bright. Am is the same neighbourhood, darker.",
  },
  {
    id: "lesson_uke_island_01",
    title: "Island strum",
    skill: "uke_island",
    trackId: "track_uke_songs",
    order: 8,
    type: "rhythm",
    objectives: ["Play D DU UDU", "Keep the hand moving"],
    chords: ["C", "G"],
    pattern: "D-DU-UDU",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_uke_cg_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Island strum",
    criteria: ["The hand keeps moving", "Land on one"],
    why: "Dock Loop with a moving hand.",
    interpret: "Keep the hand like a wave.",
  },
  {
    id: "lesson_uke_create_hang_01",
    title: "Your hang",
    skill: "uke_create",
    trackId: "track_uke_songs",
    order: 9,
    type: "song",
    objectives: ["Stay on C, or switch to G", "Play the one you picked"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_uke_cg_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["C", "C–G"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const BASS_LESSONS: Lesson[] = [
  {
    id: "lesson_bass_e_pulse_01",
    title: "E-string pulse",
    skill: "bass_pulse",
    trackId: "track_bass_foundations",
    order: 1,
    type: "warmup",
    objectives: ["One note, dead on the click"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_bass_em_root_01",
    title: "Em root",
    skill: "bass_em",
    trackId: "track_bass_roots",
    order: 2,
    type: "chord",
    objectives: ["Open E is the root of Em"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_bass_e_pulse_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_bass_g_root_01",
    title: "G root",
    skill: "bass_g",
    trackId: "track_bass_roots",
    order: 3,
    type: "chord",
    objectives: ["Third fret, E string"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_bass_em_root_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_bass_em_g_01",
    title: "The Floor",
    skill: "bass_groove",
    trackId: "track_bass_grooves",
    order: 4,
    type: "song",
    objectives: ["Change on bar one, stay fat"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_bass_g_root_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "The Floor",
    criteria: ["The loop finishes", "Stay fat on the change"],
    why: "What the kick sits on.",
    interpret: "Play it fat. Don't thin out on the change.",
  },
  {
    id: "lesson_bass_fifth_01",
    title: "Root and fifth",
    skill: "bass_fifth",
    trackId: "track_bass_techniques",
    order: 5,
    type: "skill",
    objectives: ["Next string, two frets up", "Skip the third"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 76,
    prerequisites: ["lesson_bass_em_g_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_bass_octave_01",
    title: "Octave punch",
    skill: "bass_octave",
    trackId: "track_bass_techniques",
    order: 6,
    type: "skill",
    objectives: ["Skip a string, two frets up", "Same letter, higher floor"],
    chords: ["Em"],
    pattern: "D",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_bass_fifth_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_bass_walk_01",
    title: "Walk into G",
    skill: "bass_walk",
    trackId: "track_bass_techniques",
    order: 7,
    type: "song",
    objectives: ["E, F♯, G", "Arrive from underneath"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 16,
    bpm: 72,
    prerequisites: ["lesson_bass_octave_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Walk into G",
    criteria: ["Arrive from underneath", "Land fat on G"],
    why: "The walk is how bass players change rooms.",
    interpret: "Arrive. Don't jump.",
  },
  {
    id: "lesson_bass_respond_root_01",
    title: "Same floor or different",
    skill: "bass_listen",
    trackId: "track_bass_roots",
    order: 8,
    type: "skill",
    objectives: ["Hear Em, then G", "Name same root or different"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_bass_em_g_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "The Floor",
    listenPrompt: { a: "Em", b: "G", ask: "Same root or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "The Floor uses both. Name the difference.",
  },
  {
    id: "lesson_bass_create_hang_01",
    title: "Your hang",
    skill: "bass_create",
    trackId: "track_bass_grooves",
    order: 9,
    type: "song",
    objectives: ["Stay on Em, or walk to G", "Play the one you picked"],
    chords: ["Em", "G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_bass_em_g_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["Em", "Em–G"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const DRUM_LESSONS: Lesson[] = [
  {
    id: "lesson_drums_kick_01",
    title: "Kick on one",
    skill: "kick",
    trackId: "track_drums_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Foot or pad, beat 1 only"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 80,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_drums_backbeat_01",
    title: "Backbeat",
    skill: "backbeat",
    trackId: "track_drums_groove",
    order: 2,
    type: "rhythm",
    objectives: ["Snare on 2 and 4"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 84,
    prerequisites: ["lesson_drums_kick_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_drums_four_01",
    title: "The Backbeat",
    skill: "four_floor",
    trackId: "track_drums_groove",
    order: 3,
    type: "song",
    objectives: ["Kick every beat, snare 2 and 4"],
    chords: [],
    pattern: "D",
    bars: 16,
    bpm: 88,
    prerequisites: ["lesson_drums_backbeat_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "The Backbeat",
    criteria: ["Snare on 2 and 4", "The loop finishes"],
    why: "The whole song sits on 2 and 4.",
    interpret: "The snare is the conversation.",
  },
  {
    id: "lesson_drums_respond_snare_01",
    title: "Where's the snare",
    skill: "drums_listen",
    trackId: "track_drums_groove",
    order: 4,
    type: "skill",
    objectives: ["Hear kick-only, then backbeat", "Name same groove or different"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_drums_four_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "The Backbeat",
    listenPrompt: { a: "kick", b: "backbeat", ask: "Same groove or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Find the snare. That's the conversation.",
  },
  {
    id: "lesson_drums_create_hang_01",
    title: "Your hang",
    skill: "drums_create",
    trackId: "track_drums_groove",
    order: 5,
    type: "song",
    objectives: ["Kick on one, or four on the floor", "Play the one you picked"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 84,
    prerequisites: ["lesson_drums_four_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["Kick on one", "Four on the floor"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const VOCAL_LESSONS: Lesson[] = [
  {
    id: "lesson_vocals_drone_01",
    title: "Hum the drone",
    skill: "drone",
    trackId: "track_vocals_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Match the reference C"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_vocals_match_c_01",
    title: "Match C",
    skill: "match_c",
    trackId: "track_vocals_pitch",
    order: 2,
    type: "chord",
    objectives: ["Land inside 20 cents"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_vocals_drone_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_vocals_hold_01",
    title: "The held C",
    skill: "hold",
    trackId: "track_vocals_pitch",
    order: 3,
    type: "song",
    objectives: ["One breath, one pitch, four counts"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_vocals_match_c_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "The held C",
    criteria: ["One breath", "Four counts"],
    why: "Breath is the instrument.",
    interpret: "Don't push. One breath.",
  },
  {
    id: "lesson_vocals_respond_pitch_01",
    title: "Same pitch or different",
    skill: "voice_listen",
    trackId: "track_vocals_pitch",
    order: 4,
    type: "skill",
    objectives: ["Hear C, then G", "Name same pitch or different"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_vocals_hold_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "The held C",
    listenPrompt: { a: "C", b: "G", ask: "Same pitch or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Name the move. That's listening, not a test.",
  },
  {
    id: "lesson_vocals_create_hang_01",
    title: "Your hang",
    skill: "voice_create",
    trackId: "track_vocals_pitch",
    order: 5,
    type: "song",
    objectives: ["Stay on C, or step to G", "Hold the one you picked"],
    chords: ["C", "G"],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_vocals_hold_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["C", "C–G"],
    criteria: ["You picked it", "You held it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Hold the one you picked like you meant it.",
  },
];

const MANDOLIN_LESSONS: Lesson[] = [
  {
    id: "lesson_mandolin_open_01",
    title: "Open GDAE",
    skill: "mandolin_open",
    trackId: "track_mandolin_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Pick G D A E in order", "One clean note per course"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_mandolin_g_01",
    title: "Two-finger G",
    skill: "mandolin_g",
    trackId: "track_mandolin_chords",
    order: 2,
    type: "chord",
    objectives: ["A course fret 2, E course fret 3", "Both strings of each pair"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_mandolin_open_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_mandolin_c_01",
    title: "C shape",
    skill: "mandolin_c",
    trackId: "track_mandolin_chords",
    order: 3,
    type: "chord",
    objectives: ["D course fret 2, A course fret 3", "Keep G and E open"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_mandolin_g_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_mandolin_gc_01",
    title: "Porch Light",
    skill: "mandolin_gc",
    trackId: "track_mandolin_songs",
    order: 4,
    type: "song",
    objectives: ["Change on beat 1", "Keep the wrist loose"],
    chords: ["G", "C"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_mandolin_c_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Porch Light",
    criteria: ["The loop finishes", "The change lands on one"],
    why: "Two shapes, one steady down-pick. That is a tune.",
    interpret: "Let each downstroke ring into the next.",
  },
  {
    id: "lesson_mandolin_respond_gc_01",
    title: "Same chord or different",
    skill: "mandolin_listen",
    trackId: "track_mandolin_songs",
    order: 5,
    type: "skill",
    objectives: ["Hear G, then C", "Name same chord or different"],
    chords: ["G", "C"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_mandolin_gc_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Porch Light",
    listenPrompt: { a: "G", b: "C", ask: "Same chord or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Porch Light uses both. Name the difference.",
  },
  {
    id: "lesson_mandolin_d_01",
    title: "D shape",
    skill: "mandolin_d",
    trackId: "track_mandolin_chords",
    order: 6,
    type: "chord",
    objectives: ["G course fret 2, E course fret 2", "Open D and A in the middle"],
    chords: ["D"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_mandolin_c_01"],
    masteryRequired: 0.75,
    why: "The V that pulls back to G.",
  },
  {
    id: "lesson_mandolin_chop_01",
    title: "The chop",
    skill: "mandolin_chop",
    trackId: "track_mandolin_songs",
    order: 7,
    type: "rhythm",
    objectives: ["Open down on 1 and 3", "Muted chop on 2 and 4"],
    chords: ["G", "C"],
    pattern: "D-D-",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_mandolin_gc_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Chop",
    criteria: ["The chop lands on 2 and 4", "The open strokes still ring"],
    why: "Porch Light with a backbeat.",
    interpret: "Make the chop short, like a snare.",
  },
  {
    id: "lesson_mandolin_create_hang_01",
    title: "Your hang",
    skill: "mandolin_create",
    trackId: "track_mandolin_songs",
    order: 8,
    type: "song",
    objectives: ["Stay on G, or switch to C", "Play the one you picked"],
    chords: ["G", "C"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_mandolin_gc_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["G", "G–C"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const BANJO_LESSONS: Lesson[] = [
  {
    id: "lesson_banjo_open_01",
    title: "Open gDGBD",
    skill: "banjo_open",
    trackId: "track_banjo_foundations",
    order: 1,
    type: "warmup",
    objectives: ["Pick D G B D, then the short g", "One clean note per string"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_banjo_g_01",
    title: "G is already there",
    skill: "banjo_g",
    trackId: "track_banjo_shapes",
    order: 2,
    type: "chord",
    objectives: ["Brush all five open strings", "Hear G major with no fingers down"],
    chords: ["G"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_banjo_open_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_banjo_d7_01",
    title: "D7 shape",
    skill: "banjo_d7",
    trackId: "track_banjo_shapes",
    order: 3,
    type: "chord",
    objectives: ["G string fret 2, B string fret 1, D string fret 2", "Leave the short g open"],
    chords: ["D7"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_banjo_g_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_banjo_gd7_01",
    title: "Creek Road",
    skill: "banjo_gd7",
    trackId: "track_banjo_songs",
    order: 4,
    type: "song",
    objectives: ["Change on beat 1", "Keep the thumb steady"],
    chords: ["G", "D7"],
    pattern: "D",
    bars: 16,
    bpm: 76,
    prerequisites: ["lesson_banjo_d7_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Creek Road",
    criteria: ["The loop finishes", "The change lands on one"],
    why: "Open G and one shape. That is a tune.",
    interpret: "Let the open strings ring between changes.",
  },
  {
    id: "lesson_banjo_respond_gd7_01",
    title: "Same chord or different",
    skill: "banjo_listen",
    trackId: "track_banjo_songs",
    order: 5,
    type: "skill",
    objectives: ["Hear G, then D7", "Name same chord or different"],
    chords: ["G", "D7"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_banjo_gd7_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Creek Road",
    listenPrompt: { a: "G", b: "D7", ask: "Same chord or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Creek Road uses both. Name the difference.",
  },
  {
    id: "lesson_banjo_c_01",
    title: "C shape",
    skill: "banjo_c",
    trackId: "track_banjo_shapes",
    order: 6,
    type: "chord",
    objectives: ["D string fret 2, B string fret 1, first D fret 2", "Middle G stays open"],
    chords: ["C"],
    pattern: "D",
    bars: 8,
    bpm: 70,
    prerequisites: ["lesson_banjo_d7_01"],
    masteryRequired: 0.75,
    why: "The IV that opens the loop up.",
  },
  {
    id: "lesson_banjo_roll_01",
    title: "Forward roll",
    skill: "banjo_roll",
    trackId: "track_banjo_rolls",
    order: 7,
    type: "rhythm",
    objectives: ["Thumb, index, middle in order", "Eight even notes per bar"],
    chords: ["G", "D7"],
    pattern: "DDDDDDDD",
    bars: 8,
    bpm: 80,
    prerequisites: ["lesson_banjo_gd7_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Forward roll",
    criteria: ["The roll stays even", "The chord changes on one"],
    why: "Creek Road with the right hand moving.",
    interpret: "Keep the roll rolling through the change.",
  },
  {
    id: "lesson_banjo_create_hang_01",
    title: "Your hang",
    skill: "banjo_create",
    trackId: "track_banjo_songs",
    order: 8,
    type: "song",
    objectives: ["Stay on G, or switch to D7", "Play the one you picked"],
    chords: ["G", "D7"],
    pattern: "D",
    bars: 8,
    bpm: 72,
    prerequisites: ["lesson_banjo_gd7_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["G", "G–D7"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Play the one you picked like you meant it.",
  },
];

const VIOLIN_LESSONS: Lesson[] = [
  {
    id: "lesson_violin_open_01",
    title: "Open GDAE",
    skill: "violin_open",
    trackId: "track_violin_foundations",
    order: 1,
    type: "warmup",
    objectives: ["One full bow per open string", "Bow between bridge and fingerboard"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: [],
    masteryRequired: 0.7,
  },
  {
    id: "lesson_violin_bow_pulse_01",
    title: "Down on one, up on three",
    skill: "violin_bow",
    trackId: "track_violin_foundations",
    order: 2,
    type: "rhythm",
    objectives: ["Down-bow on 1, up-bow on 3", "Count through the rests"],
    chords: [],
    pattern: "D-U-",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_violin_open_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_violin_first_finger_01",
    title: "First finger",
    skill: "violin_first_finger",
    trackId: "track_violin_position",
    order: 3,
    type: "skill",
    objectives: ["D to E, A to B", "One whole step, one finger"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_violin_open_01"],
    masteryRequired: 0.75,
  },
  {
    id: "lesson_violin_walk_01",
    title: "Evening Walk",
    skill: "violin_walk",
    trackId: "track_violin_songs",
    order: 4,
    type: "song",
    objectives: ["D E F♯ E, one bow each", "Rest on beat 4"],
    chords: [],
    pattern: "DUD-",
    bars: 16,
    bpm: 60,
    prerequisites: ["lesson_violin_first_finger_01"],
    masteryRequired: 0.75,
    process: "perform",
    repertoire: "Evening Walk",
    criteria: ["The loop finishes", "The rest keeps its full count"],
    why: "Three notes and a rest. That is a tune.",
    interpret: "Let each note fade into the rest.",
  },
  {
    id: "lesson_violin_respond_bow_01",
    title: "Same string or different",
    skill: "violin_listen",
    trackId: "track_violin_songs",
    order: 5,
    type: "skill",
    objectives: ["Hear D, then A", "Name same string or different"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_violin_walk_01"],
    masteryRequired: 0.7,
    process: "respond",
    repertoire: "Evening Walk",
    listenPrompt: { a: "D", b: "A", ask: "Same string or different?", answer: "different" },
    criteria: ["You listened first", "You named one thing"],
    why: "Evening Walk lives on D. A is the neighbour.",
  },
  {
    id: "lesson_violin_slur_01",
    title: "Two notes, one bow",
    skill: "violin_slur",
    trackId: "track_violin_position",
    order: 6,
    type: "skill",
    objectives: ["D–E in one down-bow", "F♯–G in one up-bow"],
    chords: [],
    pattern: "DU",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_violin_first_finger_01"],
    masteryRequired: 0.75,
    why: "The bow keeps moving while the finger changes.",
  },
  {
    id: "lesson_violin_create_hang_01",
    title: "Your hang",
    skill: "violin_create",
    trackId: "track_violin_songs",
    order: 7,
    type: "song",
    objectives: ["Stay on D–E, or go on to F♯", "Play the one you picked"],
    chords: [],
    pattern: "D",
    bars: 8,
    bpm: 60,
    prerequisites: ["lesson_violin_walk_01"],
    masteryRequired: 0.7,
    process: "create",
    repertoire: "Your hang",
    createOptions: ["D–E", "D–E–F♯"],
    criteria: ["You picked it", "You played it through"],
    why: "You pick the idea. That's the piece.",
    interpret: "Bow the one you picked like you meant it.",
  },
];

const TRACKS: Record<InstrumentId, { id: string; name: string }[]> = {
  guitar: [...GUITAR_TRACKS],
  piano: [
    { id: "track_piano_foundations", name: "Foundations" },
    { id: "track_piano_triads", name: "Triads" },
    { id: "track_piano_cadences", name: "Cadences" },
  ],
  ukulele: [
    { id: "track_uke_foundations", name: "Foundations" },
    { id: "track_uke_chords", name: "Open chords" },
    { id: "track_uke_songs", name: "Songs" },
  ],
  bass: [
    { id: "track_bass_foundations", name: "Foundations" },
    { id: "track_bass_roots", name: "Roots" },
    { id: "track_bass_grooves", name: "Grooves" },
    { id: "track_bass_techniques", name: "Techniques" },
  ],
  drums: [
    { id: "track_drums_foundations", name: "Foundations" },
    { id: "track_drums_groove", name: "Groove" },
  ],
  vocals: [
    { id: "track_vocals_foundations", name: "Foundations" },
    { id: "track_vocals_pitch", name: "Pitch" },
  ],
  mandolin: [
    { id: "track_mandolin_foundations", name: "Foundations" },
    { id: "track_mandolin_chords", name: "Chords" },
    { id: "track_mandolin_songs", name: "Songs" },
  ],
  banjo: [
    { id: "track_banjo_foundations", name: "Foundations" },
    { id: "track_banjo_shapes", name: "Shapes" },
    { id: "track_banjo_rolls", name: "Rolls" },
    { id: "track_banjo_songs", name: "Songs" },
  ],
  violin: [
    { id: "track_violin_foundations", name: "Foundations" },
    { id: "track_violin_position", name: "First position" },
    { id: "track_violin_songs", name: "Songs" },
  ],
};

const ALL: Record<InstrumentId, Lesson[]> = {
  guitar: GUITAR_LESSONS,
  piano: PIANO_LESSONS,
  ukulele: UKE_LESSONS,
  bass: BASS_LESSONS,
  drums: DRUM_LESSONS,
  vocals: VOCAL_LESSONS,
  mandolin: MANDOLIN_LESSONS,
  banjo: BANJO_LESSONS,
  violin: VIOLIN_LESSONS,
};

export function lessonsFor(id: InstrumentId) {
  return ALL[id];
}

export function tracksFor(id: InstrumentId) {
  return TRACKS[id];
}

export function foundationsFor(id: InstrumentId) {
  const map: Record<InstrumentId, string[]> = {
    guitar: ["lesson_guitar_orientation_01", "lesson_guitar_tuning_01", "lesson_guitar_open_strings_01"],
    piano: ["lesson_piano_middle_c_01"],
    ukulele: ["lesson_uke_open_01"],
    bass: ["lesson_bass_e_pulse_01"],
    drums: ["lesson_drums_kick_01"],
    vocals: ["lesson_vocals_drone_01"],
    mandolin: ["lesson_mandolin_open_01"],
    banjo: ["lesson_banjo_open_01"],
    violin: ["lesson_violin_open_01"],
  };
  return map[id];
}

export function promiseFor(id: InstrumentId) {
  if (id === "guitar") return GUITAR_PROMISE;
  return instrumentById(id).promise;
}

export function firstLessonIds(id: InstrumentId): [string, string, string] {
  const map: Record<InstrumentId, [string, string, string]> = {
    guitar: ["lesson_guitar_open_strings_01", "lesson_guitar_em_chord_01", "lesson_guitar_song_first_two_chord_01"],
    piano: ["lesson_piano_middle_c_01", "lesson_piano_c_triad_01", "lesson_piano_cg_cadence_01"],
    ukulele: ["lesson_uke_open_01", "lesson_uke_c_01", "lesson_uke_cg_01"],
    bass: ["lesson_bass_e_pulse_01", "lesson_bass_em_root_01", "lesson_bass_em_g_01"],
    drums: ["lesson_drums_kick_01", "lesson_drums_backbeat_01", "lesson_drums_four_01"],
    vocals: ["lesson_vocals_drone_01", "lesson_vocals_match_c_01", "lesson_vocals_hold_01"],
    mandolin: ["lesson_mandolin_open_01", "lesson_mandolin_g_01", "lesson_mandolin_gc_01"],
    banjo: ["lesson_banjo_open_01", "lesson_banjo_g_01", "lesson_banjo_gd7_01"],
    violin: ["lesson_violin_open_01", "lesson_violin_first_finger_01", "lesson_violin_walk_01"],
  };
  return map[id];
}

export function lessonByIdFor(id: InstrumentId, lessonId: string) {
  return lessonsFor(id).find((l) => l.id === lessonId) ?? lessonsFor(id)[0];
}

export function isUnlockedFor(id: InstrumentId, lessonId: string, mastery: Record<string, number>) {
  const lesson = lessonsFor(id).find((l) => l.id === lessonId);
  if (!lesson) return false;
  return lesson.prerequisites.every((p) => {
    const req = lessonsFor(id).find((l) => l.id === p)?.masteryRequired ?? 0.7;
    return (mastery[p] ?? 0) >= req;
  });
}

export function nextLessonFor(id: InstrumentId, mastery: Record<string, number>) {
  const list = lessonsFor(id);
  return list.find((l) => isUnlockedFor(id, l.id, mastery) && (mastery[l.id] ?? 0) < l.masteryRequired) ?? list[list.length - 1];
}

export const UKE_CHORDS: Record<string, { frets: (number | null)[]; fingers: (number | null)[]; notes: string[] }> = {
  C: { frets: [0, 0, 0, 3], fingers: [0, 0, 0, 3], notes: ["G", "C", "E", "C"] },
  G: { frets: [0, 2, 3, 2], fingers: [0, 1, 3, 2], notes: ["G", "D", "G", "B"] },
  Am: { frets: [2, 0, 0, 0], fingers: [2, 0, 0, 0], notes: ["A", "C", "E", "A"] },
  F: { frets: [2, 0, 1, 0], fingers: [2, 0, 1, 0], notes: ["A", "C", "F", "A"] },
  D: { frets: [2, 2, 2, 0], fingers: [1, 2, 3, 0], notes: ["A", "D", "F♯", "A"] },
};

/** Frets in G–D–A–E course order. Each course is a unison pair, treated as one string. */
export const MANDOLIN_CHORDS: Record<string, { frets: (number | null)[]; fingers: (number | null)[]; notes: string[] }> = {
  G: { frets: [0, 0, 2, 3], fingers: [0, 0, 1, 2], notes: ["G", "D", "B", "G"] },
  C: { frets: [0, 2, 3, 0], fingers: [0, 1, 2, 0], notes: ["G", "E", "C", "E"] },
  D: { frets: [2, 0, 0, 2], fingers: [1, 0, 0, 2], notes: ["A", "D", "A", "F♯"] },
  Am: { frets: [2, 2, 3, 0], fingers: [1, 2, 3, 0], notes: ["A", "E", "C", "E"] },
  Em: { frets: [0, 2, 2, 0], fingers: [0, 1, 2, 0], notes: ["G", "E", "B", "E"] },
};

/**
 * Frets in g–D–G–B–D order for a five-string banjo in open G. The short fifth
 * string (first entry) starts at fret 5 and is always shown open here.
 */
export const BANJO_CHORDS: Record<string, { frets: (number | null)[]; fingers: (number | null)[]; notes: string[] }> = {
  G: { frets: [0, 0, 0, 0, 0], fingers: [0, 0, 0, 0, 0], notes: ["g", "D", "G", "B", "D"] },
  C: { frets: [0, 2, 0, 1, 2], fingers: [0, 2, 0, 1, 3], notes: ["g", "E", "G", "C", "E"] },
  D7: { frets: [0, 0, 2, 1, 2], fingers: [0, 0, 2, 1, 3], notes: ["g", "D", "A", "C", "E"] },
  D: { frets: [0, 0, 2, 3, 4], fingers: [0, 0, 1, 2, 3], notes: ["g", "D", "A", "D", "F♯"] },
  Em: { frets: [0, 2, 0, 0, 2], fingers: [0, 1, 0, 0, 2], notes: ["g", "E", "G", "B", "E"] },
  Am: { frets: [0, 2, 2, 1, 2], fingers: [0, 2, 3, 1, 4], notes: ["g", "E", "A", "C", "E"] },
};

export const PIANO_VOICINGS: Record<string, number[]> = {
  C: [60, 64, 67],
  G: [67, 71, 74],
  Am: [57, 60, 64],
  F: [53, 57, 60],
  Em: [52, 55, 59],
  D: [62, 66, 69],
  E: [52, 56, 59],
  A: [57, 61, 64],
};

export function midiToFreq(midi: number) {
  return 440 * Math.pow(2, (midi - 69) / 12);
}

export function stringFreq(inst: InstrumentDef, stringIndex: number, fret: number) {
  const open = inst.openFreq[stringIndex] ?? inst.openFreq[0] ?? 110;
  return open * Math.pow(2, fret / 12);
}

export function withSurface(item: PlanItem, inst: InstrumentDef): PlanItem {
  return {
    ...item,
    surface: inst.surface,
    stringCount: inst.stringNames.length,
  };
}
